### ISSUE TITLE
还在维护吗

### ISSUE THREAD

**Issue by Phoebus888** [Yasil/carewebsite#2]
还在维护吗

**Comment by Yasil** [comment]
暂时没打算增加新功能什么的. 你可以自己修改!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yasil/carewebsite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月26日(星期一) 下午2:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Yasil/carewebsite] 还在维护吗 (#2)





 
还在维护吗
